[package]
name = "suika-game-audio"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_kira_audio.workspace = true
suika-game-core.workspace = true
suika-game-assets.workspace = true
