blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/itsakeyfut/suika-game/discussions
    about: Please use Discussions for questions and discussions
  - name: Documentation
    url: https://github.com/itsakeyfut/suika-game/tree/main/docs
    about: View documentation here
