[package]
name = "suika-game-core"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
bevy_rapier2d.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
